wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1642500623
    t:
      1:
      - 1
      - 5
      - 9
      2:
      - 1
      - 5
      - 9
      3:
      - 2
      4: 3.8.10
      5: 0.12.9
      8:
      - 1
      - 3
      - 5
    visualize:
      precision_recall:
        panel_config:
          fieldSettings:
            stroke: null
            x: recall_micro
            y: precision_micro
          panelDefId: wandb/line/v0
          stringSettings:
            title: Average Precision
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: precision_recall_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
