wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Train_loss_step
      5: 1
      6:
      - 1
    - 1: Acc_train
      5: 1
      6:
      - 1
    - 1: Train_F1
      5: 1
      6:
      - 1
    - 1: Val_FBeta
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: Val_loss
      5: 1
      6:
      - 1
    - 1: Acc_val
      5: 1
      6:
      - 1
    - 1: Val_F1
      5: 1
      6:
      - 1
    - 1: Val_Fbeta
      5: 1
      6:
      - 1
    - 1: Train_loss_epoch
      5: 1
      6:
      - 1
    - 1: Acc_test
      5: 1
      6:
      - 1
    - 1: Test_F1
      5: 1
      6:
      - 1
    - 1: Test_FBeta
      5: 1
      6:
      - 1
    python_version: 3.8.10
    start_time: 1642464399
    t:
      1:
      - 1
      - 5
      - 9
      2:
      - 1
      - 5
      - 9
      3:
      - 2
      - 7
      - 13
      4: 3.8.10
      5: 0.12.9
      8:
      - 1
      - 3
      - 5
input_shape:
  desc: null
  value:
  - 3
  - 256
  - 256
learning_rate:
  desc: null
  value: 0.001
num_classes:
  desc: null
  value: 2
train_dataframe:
  desc: null
  value: '                  img_id  has_oilpalm

    0     train/img_0000.jpg            0

    1     train/img_0001.jpg            0

    2     train/img_0002.jpg            0

    3     train/img_0003.jpg            0

    4     train/img_0004.jpg            0

    ...                  ...          ...

    7672  train/img_7672.jpg            0

    7673  train/img_7673.jpg            0

    7674  train/img_7674.jpg            0

    7675  train/img_7675.jpg            0

    7676  train/img_7676.jpg            0


    [7677 rows x 2 columns]'
